language: node_js
node_js:
  - 14
services:
  - docker
script:
  - docker --version
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend nchandlersmith/udagram-frontend
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push nchandlersmith/udagram-frontend
